# Generated by Django 4.2.1 on 2023-11-02 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='nommbre',
            new_name='nombre',
        ),
    ]
